api_keys:
  binance_api_key: your_binance_api_key_here
  binance_secret_key: your_binance_secret_key_here
  global_data_api_key: your_global_data_api_key_here
  market_data_api_key: your_market_data_api_key_here
  social_data_api_key: your_social_data_api_key_here
enterprise:
  ai_strategies:
    deep_learning: true
    enabled: true
  arbitrage:
    enabled: true
    multi_exchange: true
  compliance:
    enabled: true
    iso27001_mode: true
  live_trading:
    enabled: true
    institutional_mode: true
  monitoring:
    enabled: true
    processing_delay_ms: 5
    ram_usage_percentage: 85
    real_time: true
    trading_error_percentage: 0.1
  reporting:
    enabled: true
    institutional_format: true
  risk_manager:
    enabled: true
    sla_monitoring: true
model:
  batch_size: 32
  epochs: 50
  sequence_length: 60
  train_test_split: 0.8
paths:
  global_data_path: path/to/global_data
  logs_path: logs
  market_data_path: path/to/market_data
  social_data_path: path/to/social_data
risk_management:
  max_drawdown_percentage: 20.0
  stop_loss_percentage: 2.0
  take_profit_percentage: 3.0
  volatility_threshold: 0.8
trading:
  initial_capital: 10000
  instrument: XAUUSD
  max_positions: 3
  risk_percentage: 1.5
  timeframe: H1
